language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew
script:
- ./gradlew build connectedCheck

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

licenses:
- '.+'
